include: package:lint/analysis_options_package.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "example/*"
  errors:
    invalid_use_of_protected_member: error
    always_declare_return_types: error
    literal_only_boolean_expressions: ignore