name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 1.2.0
homepage: https://github.com/hivedb/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  path: ">=1.6.0 <1.7.0"
  pointycastle: ^1.0.2
  meta: ^1.1.7

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  lint: ^1.0.0
  dartx: ^0.2.0